### ISSUE TITLE
Address vulnerable dependencies

### ISSUE THREAD

**Issue by lederer** [azavea/pwd-unitybar#45]
Github found potential security vulnerabilities in this project's dependencies
https://github.com/azavea/pwd-unitybar/network/dependencies

**Comment by kellyi** [comment]
npm 6+ has an `npm audit` command which I ran to generate a list of vulnerabilities along with suggestions on how to remedy each of them. The output's too verbose to fit in a GitHub comment, but I'm going to go through them to fix them.
