### ISSUE TITLE
Add Prettier

### ISSUE THREAD

**Issue by caseycesari** [azavea/pwd-unitybar#56]
This will require:

- [x] Adding a .prettierrc.json file. We should use the [settings](https://github.com/azavea/ism-watershed-wellness-snapshot/blob/develop/src/app/.prettierrc.json) developed for ISM.
- [x] Set up the webpack configuration to include a prettier plugin which will automatically reformat code in line with prettierrc on file system changes
- [x] Modifying the eslint rules to not conflict with Prettier. It may be easiest to adopt the [rules](https://github.com/facebook/create-react-app/blob/master/.eslintrc.json) used by Create React App.
- [x] Ensuring nothing broke after Prettier modifies files.
- [x] Add documentation to the README explaining how develops can [set up their editors](https://prettier.io/docs/en/editors.html) with Prettier.

**Comment by kellyi** [comment]
Cool! Can the item about developers setting up editors to work with prettier be replaced with one about setting up webpack to prettify files automatically?

The webpack config is accessible in this project and this project's not in a Docker container now. Seems like it'd generally be easier to have the prettier formatting changes be made automatically via Webpack than it would be to rely on all developers to have prettier setup and to run prettier consistently.

**Comment by caseycesari** [comment]
Yeah, feel free to edit the list. That makes sense to me.
