### ISSUE TITLE
Staging site does not render in IE11

### ISSUE THREAD

**Issue by mmcfarland** [azavea/pwd-unitybar#86]
## Overview

We are unable to test the staging site out in IE11. It's not super important that it be available cross browser, but it would allow easier, isolated testing for browser specific bugs.

### Expected Behavior

Test site renders

### Actual Behavior

Site does not render and there are errors in the console.

### Steps to Reproduce

* Visit the site in IE11

### Demo

![Screenshot from 2019-05-17 09:40:00](https://user-images.githubusercontent.com/1014341/57932042-f3571780-7887-11e9-85b8-5ce6b8063238.png)

**Comment by kellyi** [comment]
I believe this part is intentional because we were relying on host applications to do transpilation. However, it probably makes more sense to do transpilation here.
