### ISSUE TITLE
Search button does not activate search in IE11

### ISSUE THREAD

**Issue by mmcfarland** [azavea/pwd-unitybar#87]
## Overview

When clicking on the "search" button in the unity bar, no search is performed in IE11. Hitting enter does engage the search function. This was experienced using IE11 in the Parcel Viewer. I was unable to isolate it specifically to UB due to #86 

### Expected Behavior

Search Click or Enter will start the search in all major browsers

### Actual Behavior

Search Click appears to have to effect

**Comment by kellyi** [comment]
After setting up the site to work in IE11 in #88 I checked this out and it appears that the submit handler is just not getting called in IE11.

**Comment by kellyi** [comment]
I believe hitting enter in the search box will submit it but the search button itself disappears in IE11 when the search input loses focus.
