### ISSUE TITLE
TypeError: Unable to get property 'contains' of undefined or null reference

### ISSUE THREAD

**Issue by caseycesari** [azavea/pwd-unitybar#95]
This is the most frequent error being reported for the Parcel Viewer in production.

For some reason, it is split into two items.

https://rollbar.com/pwd/ParcelViewer/items/76/
https://rollbar.com/pwd/ParcelViewer/items/68/

Unfortunately, we do not have sourcemaps for the Unity Bar when it is deployed as part of an app, so reproducing this may be difficult.

**Comment by kellyi** [comment]
We should grep the non-minified dist output for `contains`. I don't think it's from our code, so it's either in a library or something the compilation step is doing.
